[
  "amical" # AI powered dictation
  "arduino"
  "blender" # rendering engene
  "calibre"
  "claude"
  "cmux" # integrated terminal app using libghostty
  "deepl"
  "freecad"
  "firefox"
  "font-hack-nerd-font"
  "ghostty"
  "gimp"
  "github"
  "google-chrome"
  "honto"
  "inkscape"
  "karabiner-elements"
  "kobo"
  "ltspice"
  "macskk"
  "mactex"
  "microsoft-auto-update"
  "microsoft-powerpoint"
  "microsoft-teams"
  "microsoft-word"
  # "nextcloud"
  "obsidian"
  "raycast"
  "slack"
  "stats"
  "thaw" # menubar manager
  "xquartz"
  "zoom"
]
